### ISSUE TITLE
./KeyManager error (in v2)

### ISSUE THREAD

**Issue by alputv** [dannyhpy/brawlstars-nodejs#18]
KeyManager is missing... (i use brawlstars.js#v2.0.0)

![image](https://user-images.githubusercontent.com/77716705/126080401-1bce37bb-9c7d-457b-9ec6-b70239cb4f15.png)

**Comment by alputv** [comment]
Fixed this issue. Please check #19 .

**Comment by dannyhpy** [comment]
#19 has been merged! Thank you! :)
